// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/command.proto

package commandpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Operation type
type Command_OpType int32

const (
	Command_UNKNOWN Command_OpType = 0
	Command_SET     Command_OpType = 1
	Command_DELETE  Command_OpType = 2
	Command_GET     Command_OpType = 3 // linearizable reads
)

// Enum value maps for Command_OpType.
var (
	Command_OpType_name = map[int32]string{
		0: "UNKNOWN",
		1: "SET",
		2: "DELETE",
		3: "GET",
	}
	Command_OpType_value = map[string]int32{
		"UNKNOWN": 0,
		"SET":     1,
		"DELETE":  2,
		"GET":     3,
	}
)

func (x Command_OpType) Enum() *Command_OpType {
	p := new(Command_OpType)
	*p = x
	return p
}

func (x Command_OpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command_OpType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_command_proto_enumTypes[0].Descriptor()
}

func (Command_OpType) Type() protoreflect.EnumType {
	return &file_proto_command_proto_enumTypes[0]
}

func (x Command_OpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command_OpType.Descriptor instead.
func (Command_OpType) EnumDescriptor() ([]byte, []int) {
	return file_proto_command_proto_rawDescGZIP(), []int{0, 0}
}

// Command represents a key-value operation
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            Command_OpType         `protobuf:"varint,1,opt,name=op,proto3,enum=commandpb.Command_OpType" json:"op,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ClientId      string                 `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RequestId     uint64                 `protobuf:"varint,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_command_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetOp() Command_OpType {
	if x != nil {
		return x.Op
	}
	return Command_UNKNOWN
}

func (x *Command) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Command) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Command) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Command) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Command) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

// SnapshotData represents the KV store state in a snapshot
type SnapshotData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Data             map[string]string      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LastAppliedIndex uint64                 `protobuf:"varint,2,opt,name=last_applied_index,json=lastAppliedIndex,proto3" json:"last_applied_index,omitempty"`
	LastAppliedTerm  uint64                 `protobuf:"varint,3,opt,name=last_applied_term,json=lastAppliedTerm,proto3" json:"last_applied_term,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SnapshotData) Reset() {
	*x = SnapshotData{}
	mi := &file_proto_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotData) ProtoMessage() {}

func (x *SnapshotData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotData.ProtoReflect.Descriptor instead.
func (*SnapshotData) Descriptor() ([]byte, []int) {
	return file_proto_command_proto_rawDescGZIP(), []int{1}
}

func (x *SnapshotData) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SnapshotData) GetLastAppliedIndex() uint64 {
	if x != nil {
		return x.LastAppliedIndex
	}
	return 0
}

func (x *SnapshotData) GetLastAppliedTerm() uint64 {
	if x != nil {
		return x.LastAppliedTerm
	}
	return 0
}

func (x *SnapshotData) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_proto_command_proto protoreflect.FileDescriptor

const file_proto_command_proto_rawDesc = "" +
	"\n" +
	"\x13proto/command.proto\x12\tcommandpb\"\xeb\x01\n" +
	"\aCommand\x12)\n" +
	"\x02op\x18\x01 \x01(\x0e2\x19.commandpb.Command.OpTypeR\x02op\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tclient_id\x18\x05 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\x04R\trequestId\"3\n" +
	"\x06OpType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03SET\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x02\x12\a\n" +
	"\x03GET\x10\x03\"\xf7\x01\n" +
	"\fSnapshotData\x125\n" +
	"\x04data\x18\x01 \x03(\v2!.commandpb.SnapshotData.DataEntryR\x04data\x12,\n" +
	"\x12last_applied_index\x18\x02 \x01(\x04R\x10lastAppliedIndex\x12*\n" +
	"\x11last_applied_term\x18\x03 \x01(\x04R\x0flastAppliedTerm\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B9Z7github.com/Xenn-00/distributed-kv-store/proto/commandpbb\x06proto3"

var (
	file_proto_command_proto_rawDescOnce sync.Once
	file_proto_command_proto_rawDescData []byte
)

func file_proto_command_proto_rawDescGZIP() []byte {
	file_proto_command_proto_rawDescOnce.Do(func() {
		file_proto_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_command_proto_rawDesc), len(file_proto_command_proto_rawDesc)))
	})
	return file_proto_command_proto_rawDescData
}

var file_proto_command_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_command_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_command_proto_goTypes = []any{
	(Command_OpType)(0),  // 0: commandpb.Command.OpType
	(*Command)(nil),      // 1: commandpb.Command
	(*SnapshotData)(nil), // 2: commandpb.SnapshotData
	nil,                  // 3: commandpb.SnapshotData.DataEntry
}
var file_proto_command_proto_depIdxs = []int32{
	0, // 0: commandpb.Command.op:type_name -> commandpb.Command.OpType
	3, // 1: commandpb.SnapshotData.data:type_name -> commandpb.SnapshotData.DataEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_command_proto_init() }
func file_proto_command_proto_init() {
	if File_proto_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_command_proto_rawDesc), len(file_proto_command_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_command_proto_goTypes,
		DependencyIndexes: file_proto_command_proto_depIdxs,
		EnumInfos:         file_proto_command_proto_enumTypes,
		MessageInfos:      file_proto_command_proto_msgTypes,
	}.Build()
	File_proto_command_proto = out.File
	file_proto_command_proto_goTypes = nil
	file_proto_command_proto_depIdxs = nil
}
